apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-db
  namespace: main-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 891377021190.dkr.ecr.ap-northeast-2.amazonaws.com/main-db:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: mypassword
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: main-db
  namespace: main-namespace
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
