apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
  namespace: main-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
        - name: main-server
          image: sodasu/dlb-main
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: main-server
  namespace: main-namespace
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: main-server