apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
  namespace: main-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
        - name: main-server
          image: 891377021190.dkr.ecr.ap-northeast-2.amazonaws.com/main-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: main-server
  namespace: main-namespace
spec:
  selector:
    app: main-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http